"""Summarize every docs/spikes/llm-*.json run into one comparison table.

    python spikes/summarize_llm.py            # print the table
    python spikes/summarize_llm.py --write    # also write docs/spikes/llm-results.md

Reads only the evidence files already in the repo, so the table can be regenerated by anyone.
Older files from earlier versions of the script lack some fields and show "n/a".
"""

from __future__ import annotations

import argparse
import json
import statistics
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COLUMNS = [
    "Run", "Ctx", "Temp", "Rep. penalty", "Format", "Concise", "Prompt", "Trials",
    "Ended normally", "Valid JSON", "Median tokens", "Median total (s)", "Gen tok/s",
    "Prefill tok/s", "Free RAM before (GB)", "Lowest free (GB)",
]  # fmt: skip


def _count(trials: list[dict], key: str) -> str:
    if not trials or any(key not in t for t in trials):
        return "n/a"
    return f"{sum(bool(t[key]) for t in trials)}/{len(trials)}"


def row_for(path: Path) -> list[str]:
    data = json.loads(path.read_text(encoding="utf-8"))
    trials = data.get("trials", [])
    settings = data.get("settings", {})
    summary = data.get("summary", {})
    env = data.get("environment", {})

    ended = "n/a"
    if trials and all("truncated" in t for t in trials):
        ended = f"{sum(not t['truncated'] for t in trials)}/{len(trials)}"
    tokens = [t["generated_tokens"] for t in trials if "generated_tokens" in t]
    prompt_varied = trials[0].get("prompt_varied") if trials else None
    name = path.stem.removeprefix("llm-medgemma-4b-").removeprefix("llm-")

    def show(value, default="n/a"):
        return default if value is None else str(value)

    return [
        name,
        show(settings.get("num_ctx")),
        show(settings.get("temperature")),
        show(settings.get("repeat_penalty"), "none"),
        show(trials[0].get("format_mode") if trials else None, "json"),
        show(trials[0].get("concise_prompt") if trials else None, "no"),
        {True: "varied", False: "identical", None: "identical (old)"}[prompt_varied],
        str(len(trials)),
        ended,
        _count(trials, "valid_soap_json"),
        show(round(statistics.median(tokens)) if tokens else None),
        show(summary.get("warm_median_wall_seconds")),
        show(summary.get("warm_median_generation_tokens_per_s")),
        show(summary.get("warm_median_prefill_tokens_per_s")),
        show(env.get("ram_available_before_gb")),
        show(summary.get("lowest_available_ram_gb")),
    ]


def build_table(spike_dir: Path) -> str:
    rows = [row_for(p) for p in sorted(spike_dir.glob("llm-*.json"))]
    lines = ["| " + " | ".join(COLUMNS) + " |", "|" + "---|" * len(COLUMNS)]
    lines += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--dir", type=Path, default=ROOT / "docs" / "spikes")
    parser.add_argument("--write", action="store_true", help="write docs/spikes/llm-results.md")
    args = parser.parse_args(argv)

    table = build_table(args.dir)
    print(table)
    if args.write:
        out = args.dir / "llm-results.md"
        out.write_text(
            "# MedGemma runs through Ollama (reference PC)\n\n"
            "Generated by `python spikes/summarize_llm.py --write` from the JSON files in this "
            'folder. "Free RAM before" below about 4 GB means the run was under memory '
            "pressure. One PC, synthetic input, 1 to 3 trials per run.\n\n" + table + "\n",
            encoding="utf-8",
        )
        print(f"\nWrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
